version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: run
      POSTGRES_PASSWORD: run
      POSTGRES_DB: runtrack
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
