Makefile

automatiza tarefas repetitivas (rodar app, testes, lint).

Atalhos para:
make run,
make test,
make lint.


Júnior deve aprender automação de tarefas.

Usei para simplificar comando repetitivo.